package it.unipi.myfuture.myfuture_backend.dto.analytics;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO used for net financial flow generated by buy and sell operations aggregation (in transaction collection).
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserFinancialFlowDTO {
    private Long userId;            // userID
    private Double netFlow;         // (sum SELL) - (sum BUY)
    private Double totalBought;     // total volume in money for buy transaction
    private Double totalSold;       // total volume in money for sell transaction
}
